version: '3.8'
services:
  da_four:
    image: node:alpine
    container_name: da_four
    entrypoint: /bin/sh
    ports:
      - "3000:3000"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true